# Generated by Django 3.0.7 on 2020-06-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_bank_task2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('serial_number_doc', models.CharField(max_length=255, verbose_name='Серия документа')),
                ('number_doc', models.CharField(db_index=True, max_length=255, verbose_name='Номер документа')),
                ('status', models.CharField(max_length=150, verbose_name='Статус')),
                ('date_incident', models.DateTimeField(verbose_name='Дата события')),
                ('date_recording', models.DateTimeField(verbose_name='Дата записи')),
                ('ovd', models.CharField(max_length=150, verbose_name='Орган регистрации события')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_bank_task2.DocumentType', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Потерянный документ',
                'verbose_name_plural': 'Потерянные документы',
            },
        ),
        migrations.DeleteModel(
            name='LostDocuments',
        ),
    ]
